version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data:/var/lib/kafka/data
      - ./scripts:/scripts
      - ./topics.txt:/topics.txt
    depends_on:
      - zookeeper
    command:
      - sh
      - -c
      - |
        /etc/confluent/docker/run &

        /scripts/wait-for-it.sh -t 60 kafka:9092 -- echo "Kafka is ready!"

        chmod +x /scripts/create-topics.sh && /scripts/create-topics.sh

        wait
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
